# Generated by Django 4.2.5 on 2024-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=3)),
                ('source', models.CharField(max_length=64)),
            ],
        ),
    ]
